var ATTRIBUTES = [
    {
        "id": "9NVIBHDJ0U1UIVAFWVYC",
        "label": "alignment",
        "displaySyntax": "alignment",
        "syntax": "this.tempObject('dummy_data.widget.text.alignment')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "string",
        "storeType": "tempObject",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.tempObject.dummy_data.widget.text.alignment",
        'value': '<span class="IntelliTextEditor-argument">this.tempObject(\'dummy_data.widget.text.alignment\')</span>'
    },
    {
        "id": "B1LX7EYVE5PGH23OMD5R",
        "label": "hOffset",
        "displaySyntax": "hOffset",
        "syntax": "this.workVariable('dummy_data2.image.hOffset')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "number",
        "storeType": "workVar",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.workVar.dummy_data2.image.hOffset"
    },
    {
        "id": "8GYLD2IV7APMKPBBBZRJ",
        "label": "name",
        "displaySyntax": "name",
        "syntax": "this.tempObject('two.name')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "26314113394031325343",
        "returnType": "string",
        "storeType": "tempObject",
        "path": "Sha_GD8_RS.Sha_C19_RS.two.tempObject.two.name"
    },
    {
        "id": "C1IVBNBTW4HGAK87KE4D",
        "label": "text",
        "displaySyntax": "text",
        "syntax": "this.tempObject('dummy_data.widget.text')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "object",
        "storeType": "tempObject",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.tempObject.dummy_data.widget.text"
    },
    {
        "id": "43NVI3Z63FDDINSINIBF",
        "label": "data",
        "displaySyntax": "data",
        "syntax": "this.tempObject('dummy_data.widget.text.data')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "string",
        "storeType": "tempObject",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.tempObject.dummy_data.widget.text.data"
    },
    {
        "id": "NJLAAAAHYUIXD4LKX7X3",
        "label": "name",
        "displaySyntax": "name",
        "syntax": "this.tempObject('dummy_data.widget.text.name')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "string",
        "storeType": "tempObject",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.tempObject.dummy_data.widget.text.name"
    },
    {
        "id": "A81J1ULQOW8IHDZ7ML4L",
        "label": "size",
        "displaySyntax": "size",
        "syntax": "this.tempObject('dummy_data.widget.text.size')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "number",
        "storeType": "tempObject",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.tempObject.dummy_data.widget.text.size"
    },
    {
        "id": "BLVMAZ56ZRVPYXDR2HP6",
        "label": "onMouseUp",
        "displaySyntax": "onMouseUp",
        "syntax": "this.tempObject('dummy_data.widget.text.onMouseUp')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "string",
        "storeType": "tempObject",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.tempObject.dummy_data.widget.text.onMouseUp"
    },
    {
        "id": "HH2VGF6M9S7TLCKYWGS5",
        "label": "src",
        "displaySyntax": "src",
        "syntax": "this.workVariable('dummy_data2.image.src')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "string",
        "storeType": "workVar",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.workVar.dummy_data2.image.src"
    },
    {
        "id": "78DLIDZ9UKVOIQMWY87M",
        "label": "vOffset",
        "displaySyntax": "vOffset",
        "syntax": "this.workVariable('dummy_data2.image.vOffset')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "number",
        "storeType": "workVar",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.workVar.dummy_data2.image.vOffset"
    },
    {
        "id": "3KQP3LZHT76C0JQATKLA",
        "label": "hello",
        "displaySyntax": "hello",
        "syntax": "this.tempObject('dummy_data.widget.text.hello')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "string",
        "storeType": "tempObject",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.tempObject.dummy_data.widget.text.hello"
    },
    {
        "id": "LD0N4L9J1414NHU1AXJS",
        "label": "style",
        "displaySyntax": "style",
        "syntax": "this.tempObject('dummy_data.widget.text.style')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "string",
        "storeType": "tempObject",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.tempObject.dummy_data.widget.text.style"
    },
    {
        "id": "7EKIFCKCL7OLJ9EOKJN5",
        "label": "alignment",
        "displaySyntax": "alignment",
        "syntax": "this.workVariable('dummy_data2.image.alignment')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "string",
        "storeType": "workVar",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.workVar.dummy_data2.image.alignment"
    },
    {
        "id": "B7GKT3OMZJQ61MOS95S5",
        "label": "widget",
        "displaySyntax": "widget",
        "syntax": "this.tempObject('dummy_data.widget')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "object",
        "storeType": "tempObject",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.tempObject.dummy_data.widget"
    },
    {
        "id": "NEO401SM7IJ6OV1H2ERL",
        "label": "hOffset",
        "displaySyntax": "hOffset",
        "syntax": "this.tempObject('dummy_data.widget.text.hOffset')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "number",
        "storeType": "tempObject",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.tempObject.dummy_data.widget.text.hOffset"
    },
    {
        "id": "4YK8DDTVOJJZFUIE5EQG",
        "label": "vOffset",
        "displaySyntax": "vOffset",
        "syntax": "this.tempObject('dummy_data.widget.text.vOffset')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "number",
        "storeType": "tempObject",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.tempObject.dummy_data.widget.text.vOffset"
    },
    {
        "id": "1OSTD0IUV1QATFXDYNB2",
        "label": "image",
        "displaySyntax": "image",
        "syntax": "this.workVariable('dummy_data2.image')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "object",
        "storeType": "workVar",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.workVar.dummy_data2.image"
    },
    {
        "id": "QR9I2VL8663I2B2CJLQ1",
        "label": "name",
        "displaySyntax": "name",
        "syntax": "this.workVariable('dummy_data2.image.name')",
        "type": "ATTRIBUTE",
        "description": "",
        "hint": "",
        "workspaceId": "91817431040120303690",
        "returnType": "string",
        "storeType": "workVar",
        "path": "Vip_BFT_RS.Vip_OLI_RS.Coll_3.workVar.dummy_data2.image.name"
    }
]